"""Transactions

Revision ID: 2f119758200b
Revises: 6abdb9ee591e
Create Date: 2026-01-19 10:11:41.884240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f119758200b'
down_revision: Union[str, Sequence[str], None] = '6abdb9ee591e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('motive', sa.String(length=255), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('bank_date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category1_id', sa.UUID()),
    sa.Column('category2_id', sa.UUID()),
    sa.Column('category3_id', sa.UUID()),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category1_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category2_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category3_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_date', 'motive', 'to', 'bank_date', 'type', 'amount', 'user_id', 'category1_id', 'category2_id', 'category3_id', name='uq_transaction_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
